StartupEvents.registry('item', event => {
	event.create('deceasedcraft:flyer_multi_policestation')
		.texture('deceasedcraft:item/flyer')
		.texture('deceasedcraft:item/flyer')
		.maxStackSize(1)
		.rarity('rare')

	event.create('deceasedcraft:flyer_multi_polyclinic')
		.texture('deceasedcraft:item/flyer')
		.texture('deceasedcraft:item/flyer')
		.maxStackSize(1)
		.rarity('rare')

	event.create('deceasedcraft:flyer_multi_communitycenter')
		.texture('deceasedcraft:item/flyer')
		.texture('deceasedcraft:item/flyer')
		.maxStackSize(1)
		.rarity('rare')

	event.create('deceasedcraft:flyer_multi_workshop')
		.texture('deceasedcraft:item/flyer')
		.texture('deceasedcraft:item/flyer')
		.maxStackSize(1)
		.rarity('rare')

	event.create('deceasedcraft:flyer_multi_timbertower')
		.texture('deceasedcraft:item/flyer')
		.texture('deceasedcraft:item/flyer')
		.maxStackSize(1)
		.rarity('rare')

	event.create('deceasedcraft:flyer_multi_officethefirst')
		.texture('deceasedcraft:item/flyer')
		.texture('deceasedcraft:item/flyer')
		.maxStackSize(1)
		.rarity('rare')

	event.create('deceasedcraft:flyer_multi_filmworkstower')
		.texture('deceasedcraft:item/flyer')
		.texture('deceasedcraft:item/flyer')
		.maxStackSize(1)
		.rarity('rare')

	event.create('deceasedcraft:flyer_multi_courtyardofficetower')
		.texture('deceasedcraft:item/flyer')
		.texture('deceasedcraft:item/flyer')
		.maxStackSize(1)
		.rarity('rare')

	event.create('deceasedcraft:flyer_multi_sunkenclub')
		.texture('deceasedcraft:item/flyer')
		.texture('deceasedcraft:item/flyer')
		.maxStackSize(1)
		.rarity('rare')

	event.create('deceasedcraft:flyer_multi_sunkenmonumentpark')
		.texture('deceasedcraft:item/flyer')
		.texture('deceasedcraft:item/flyer')
		.maxStackSize(1)
		.rarity('rare')

	event.create('deceasedcraft:flyer_multi_gallery')
		.texture('deceasedcraft:item/flyer')
		.texture('deceasedcraft:item/flyer')
		.maxStackSize(1)
		.rarity('rare')

	event.create('deceasedcraft:flyer_multi_casino')
		.texture('deceasedcraft:item/flyer')
		.texture('deceasedcraft:item/flyer')
		.maxStackSize(1)
		.rarity('rare')

	event.create('deceasedcraft:flyer_multi_thering')
		.texture('deceasedcraft:item/flyer')
		.texture('deceasedcraft:item/flyer')
		.maxStackSize(1)
		.rarity('rare')

	event.create('deceasedcraft:flyer_multi_taigaresidence')
		.texture('deceasedcraft:item/flyer')
		.texture('deceasedcraft:item/flyer')
		.maxStackSize(1)
		.rarity('rare')

	event.create('deceasedcraft:flyer_multi_oasiscondo')
		.texture('deceasedcraft:item/flyer')
		.texture('deceasedcraft:item/flyer')
		.maxStackSize(1)
		.rarity('rare')

	event.create('deceasedcraft:flyer_multi_verticalschool')
		.texture('deceasedcraft:item/flyer')
		.texture('deceasedcraft:item/flyer')
		.maxStackSize(1)
		.rarity('rare')

	event.create('deceasedcraft:flyer_multi_flatapartment')
		.texture('deceasedcraft:item/flyer')
		.texture('deceasedcraft:item/flyer')
		.maxStackSize(1)
		.rarity('rare')

	event.create('deceasedcraft:flyer_multi_policeapartment')
		.texture('deceasedcraft:item/flyer')
		.texture('deceasedcraft:item/flyer')
		.maxStackSize(1)
		.rarity('rare')

	event.create('deceasedcraft:flyer_multi_flatmedium')
		.texture('deceasedcraft:item/flyer')
		.texture('deceasedcraft:item/flyer')
		.maxStackSize(1)
		.rarity('rare')

	event.create('deceasedcraft:flyer_multi_hospitaldamaged')
		.texture('deceasedcraft:item/flyer')
		.texture('deceasedcraft:item/flyer')
		.maxStackSize(1)
		.rarity('rare')

	event.create('deceasedcraft:flyer_multi_cafe')
		.texture('deceasedcraft:item/flyer')
		.texture('deceasedcraft:item/flyer')
		.maxStackSize(1)
		.rarity('rare')

	event.create('deceasedcraft:flyer_multi_convenientstore')
		.texture('deceasedcraft:item/flyer')
		.texture('deceasedcraft:item/flyer')
		.maxStackSize(1)
		.rarity('rare')

	event.create('deceasedcraft:flyer_multi_gunstore')
		.texture('deceasedcraft:item/flyer')
		.texture('deceasedcraft:item/flyer')
		.maxStackSize(1)
		.rarity('rare')

	event.create('deceasedcraft:flyer_multi_hospital')
		.texture('deceasedcraft:item/flyer')
		.texture('deceasedcraft:item/flyer')
		.maxStackSize(1)
		.rarity('rare')

	event.create('deceasedcraft:flyer_multi_terraceplaza')
		.texture('deceasedcraft:item/flyer')
		.texture('deceasedcraft:item/flyer')
		.maxStackSize(1)
		.rarity('rare')


 })