ServerEvents.tags('item', event => {
	event.add('forge:mediumxpfood', 'apocalypsenow:cereal')
	event.add('forge:mediumxpfood', 'apocalypsenow:donut')
	event.add('forge:mediumxpfood', 'apocalypsenow:fries')
	event.add('forge:mediumxpfood', 'apocalypsenow:nutrition_bar')
	event.add('forge:mediumxpfood', 'create:bar_of_chocolate')
	event.add('forge:mediumxpfood', 'create:chocolate_glazed_berries')
	event.add('forge:mediumxpfood', 'create:honeyed_apple')
	event.add('forge:mediumxpfood', 'create:sweet_roll')
	event.add('forge:mediumxpfood', 'farmersdelight:barbecue_stick')
	event.add('forge:mediumxpfood', 'farmersdelight:bone_broth')
	event.add('forge:mediumxpfood', 'farmersdelight:cabbage_rolls')
	event.add('forge:mediumxpfood', 'farmersdelight:cod_roll')
	event.add('forge:mediumxpfood', 'farmersdelight:cooked_rice')
	event.add('forge:mediumxpfood', 'farmersdelight:dog_food')
	event.add('forge:mediumxpfood', 'farmersdelight:dumplings')
	event.add('forge:mediumxpfood', 'farmersdelight:egg_sandwich')
	event.add('forge:mediumxpfood', 'farmersdelight:glow_berry_custard')
	event.add('forge:mediumxpfood', 'farmersdelight:mutton_wrap')
	event.add('forge:mediumxpfood', 'farmersdelight:nether_salad')
	event.add('forge:mediumxpfood', 'farmersdelight:salmon_roll')
	event.add('forge:mediumxpfood', 'farmersdelight:smoked_ham')
	event.add('forge:mediumxpfood', 'farmersdelight:stuffed_potato')
	event.add('forge:mediumxpfood', 'minecraft:rabbit_stew')
	event.add('forge:mediumxpfood', 'minecraft:golden_apple')
	event.add('forge:mediumxpfood', 'minecraft:beetroot_soup')
})