EntityJSEvents.attributes(event => {
	event.modify('minecraft:zombie', entity => { 
		entity.add("minecraft:generic.max_health", 20.0)
		entity.add("minecraft:generic.attack_damage", 3.0)
		entity.add("minecraft:generic.armor", 2.0)
		entity.add("minecraft:generic.movement_speed", 0.23)
		entity.add("minecraft:generic.follow_range", 26.0)
	})
	event.modify('zombie_extreme:crawler', entity => { 
		entity.add("minecraft:generic.max_health", 20.0)
		entity.add("minecraft:generic.attack_damage", 4.0)
		entity.add("minecraft:generic.armor", 2.0)
		entity.add("minecraft:generic.movement_speed", 0.18)
		entity.add("minecraft:generic.follow_range", 20.0)
	})
	event.modify('undead_revamp2:thesmoker', entity => { 
		entity.add("minecraft:generic.max_health", 25.0)
		entity.add("minecraft:generic.attack_damage", 4.0)
		entity.add("minecraft:generic.armor", 2.0)
		entity.add("minecraft:generic.movement_speed", 0.22)
		entity.add("minecraft:generic.follow_range", 26.0)
	})
	event.modify('zombie_extreme:infected_police', entity => { 
		entity.add("minecraft:generic.max_health", 35.0)
		entity.add("minecraft:generic.attack_damage", 3.0)
		entity.add("minecraft:generic.armor", 4.0)
		entity.add("minecraft:generic.movement_speed", 0.22)
		entity.add("minecraft:generic.follow_range", 26.0)
	})
	event.modify('undead_revamp2:bomber', entity => { 
		entity.add("minecraft:generic.max_health", 40.0)
		entity.add("minecraft:generic.attack_damage", 2.0)
		entity.add("minecraft:generic.armor", 4.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
		entity.add("minecraft:generic.follow_range", 26.0)
	})
	event.modify('undead_revamp2:theordure', entity => { 
		entity.add("minecraft:generic.max_health", 40.0)
		entity.add("minecraft:generic.attack_damage", 0.0)
		entity.add("minecraft:generic.armor", 4.0)
		entity.add("minecraft:generic.movement_speed", 0.3)
		entity.add("minecraft:generic.follow_range", 12.0)
	})
	event.modify('undead_revamp2:therod', entity => { 
		entity.add("minecraft:generic.max_health", 40.0)
		entity.add("minecraft:generic.attack_damage", 5.0)
		entity.add("minecraft:generic.armor", 4.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
		entity.add("minecraft:generic.follow_range", 32.0)
	})
	event.modify('undead_revamp2:the_moonflower', entity => { 
		entity.add("minecraft:generic.max_health", 40.0)
		entity.add("minecraft:generic.attack_damage", 7.0)
		entity.add("minecraft:generic.armor", 6.0)
		entity.add("minecraft:generic.movement_speed", 0.3)
		entity.add("minecraft:generic.follow_range", 128.0)
		entity.add("forge:step_height_addition", 1.0)
	})
	event.modify('undead_revamp2:thehunter', entity => { 
		entity.add("minecraft:generic.max_health", 40.0)
		entity.add("minecraft:generic.attack_damage", 5.0)
		entity.add("minecraft:generic.armor", 4.0)
		entity.add("minecraft:generic.movement_speed", 0.26)
		entity.add("minecraft:generic.follow_range", 96.0)
		entity.add("forge:step_height_addition", 1.0)
	})
	event.modify('undead_revamp2:thespitter', entity => { 
		entity.add("minecraft:generic.max_health", 50.0)
		entity.add("minecraft:generic.attack_damage", 8.0)
		entity.add("minecraft:generic.armor", 6.0)
		entity.add("minecraft:generic.movement_speed", 0.3)
		entity.add("minecraft:generic.follow_range", 32.0)
	})
	event.modify('zombie_extreme:boomer', entity => { 
		entity.add("minecraft:generic.max_health", 70.0)
		entity.add("minecraft:generic.attack_damage", 7.0)
		entity.add("minecraft:generic.armor", 12.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
		entity.add("minecraft:generic.follow_range", 48.0)
	})
	event.modify('undead_revamp2:theskeeper', entity => { 
		entity.add("minecraft:generic.max_health", 50.0)
		entity.add("minecraft:generic.attack_damage", 8.0)
		entity.add("minecraft:generic.armor", 6.0)
		entity.add("minecraft:generic.movement_speed", 0.25)
		entity.add("minecraft:generic.follow_range", 32.0)
	})
	event.modify('zombie_extreme:clicker', entity => { 
		entity.add("minecraft:generic.max_health", 60.0)
		entity.add("minecraft:generic.attack_damage", 8.0)
		entity.add("minecraft:generic.armor", 8.0)
		entity.add("minecraft:generic.movement_speed", 0.24)
		entity.add("minecraft:generic.follow_range", 48.0)
	})
	event.modify('undead_revamp2:theswarmer', entity => { 
		entity.add("minecraft:generic.max_health", 50.0)
		entity.add("minecraft:generic.attack_damage", 8.0)
		entity.add("minecraft:generic.armor", 6.0)
		entity.add("minecraft:generic.movement_speed", 0.25)
		entity.add("minecraft:generic.follow_range", 32.0)
	})
	event.modify('undead_revamp2:thepregnant', entity => { 
		entity.add("minecraft:generic.max_health", 140.0)
		entity.add("minecraft:generic.attack_damage", 12.0)
		entity.add("minecraft:generic.armor", 10.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
		entity.add("minecraft:generic.follow_range", 64.0)
	})
	event.modify('undead_revamp2:thegliter', entity => { 
		entity.add("minecraft:generic.max_health", 100.0)
		entity.add("minecraft:generic.attack_damage", 10.0)
		entity.add("minecraft:generic.armor", 14.0)
		entity.add("minecraft:generic.movement_speed", 0.3)
		entity.add("minecraft:generic.follow_range", 128.0)
		entity.add("forge:step_height_addition", 1.0)
	})
	event.modify('undead_revamp2:thelurker', entity => { 
		entity.add("minecraft:generic.max_health", 220.0)
		entity.add("minecraft:generic.attack_damage", 14.0)
		entity.add("minecraft:generic.armor", 12.0)
		entity.add("minecraft:generic.movement_speed", 0.35)
		entity.add("minecraft:generic.follow_range", 24.0)
		entity.add("forge:step_height_addition", 2.0)
	})
	event.modify('undead_revamp2:lechery', entity => { 
		entity.add("minecraft:generic.max_health", 180.0)
		entity.add("minecraft:generic.attack_damage", 10.0)
		entity.add("minecraft:generic.armor", 8.0)
		entity.add("minecraft:generic.movement_speed", 0.42)
		entity.add("minecraft:generic.follow_range", 48.0)
		entity.add("forge:step_height_addition", 3.0)
	})
	event.modify('zombie_extreme:infected_military', entity => { 
		entity.add("minecraft:generic.max_health", 80.0)
		entity.add("minecraft:generic.attack_damage", 8.0)
		entity.add("minecraft:generic.armor", 20.0)
		entity.add("minecraft:generic.movement_speed", 0.25)
		entity.add("minecraft:generic.follow_range", 48.0)
	})
	event.modify('undead_revamp2:sucker', entity => { 
		entity.add("minecraft:generic.max_health", 40.0)
		entity.add("minecraft:generic.attack_damage", 7.0)
		entity.add("minecraft:generic.armor", 6.0)
		entity.add("minecraft:generic.movement_speed", 0.4)
		entity.add("minecraft:generic.follow_range", 96.0)
	})
	event.modify('zombie_extreme:inflated', entity => { 
		entity.add("minecraft:generic.max_health", 60.0)
		entity.add("minecraft:generic.attack_damage", 7.0)
		entity.add("minecraft:generic.armor", 16.0)
		entity.add("minecraft:generic.movement_speed", 0.18)
		entity.add("minecraft:generic.follow_range", 48.0)
	})
	event.modify('zombie_extreme:infected_hazmat', entity => { 
		entity.add("minecraft:generic.max_health", 70.0)
		entity.add("minecraft:generic.attack_damage", 10.0)
		entity.add("minecraft:generic.armor", 24.0)
		entity.add("minecraft:generic.movement_speed", 0.22)
		entity.add("minecraft:generic.follow_range", 48.0)
	})
	event.modify('undead_revamp2:therabidus', entity => { 
		entity.add("minecraft:generic.max_health", 50.0)
		entity.add("minecraft:generic.attack_damage", 12.0)
		entity.add("minecraft:generic.armor", 12.0)
		entity.add("minecraft:generic.movement_speed", 3.8)
		entity.add("minecraft:generic.follow_range", 32.0)
	})
	event.modify('zombie_extreme:infected_juggernaut', entity => { 
		entity.add("minecraft:generic.max_health", 160.0)
		entity.add("minecraft:generic.attack_damage", 14.0)
		entity.add("minecraft:generic.armor", 30.0)
		entity.add("minecraft:generic.movement_speed", 0.25)
		entity.add("minecraft:generic.follow_range", 64.0)
	})
	event.modify('zombie_extreme:goon', entity => { 
		entity.add("minecraft:generic.max_health", 90.0)
		entity.add("minecraft:generic.attack_damage", 12.0)
		entity.add("minecraft:generic.armor", 26.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
		entity.add("minecraft:generic.follow_range", 64.0)
	})
	event.modify('zombie_extreme:revived', entity => { 
		entity.add("minecraft:generic.max_health", 90.0)
		entity.add("minecraft:generic.attack_damage", 11.0)
		entity.add("minecraft:generic.armor", 26.0)
		entity.add("minecraft:generic.movement_speed", 0.3)
		entity.add("minecraft:generic.follow_range", 64.0)
	})
	event.modify('zombie_extreme:faceless', entity => { 
		entity.add("minecraft:generic.max_health", 90.0)
		entity.add("minecraft:generic.attack_damage", 12.0)
		entity.add("minecraft:generic.armor", 26.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
		entity.add("minecraft:generic.follow_range", 64.0)
		entity.add("forge:step_height_addition", 1.0)
	})
	event.modify('zombie_extreme:night_hunter', entity => { 
		entity.add("minecraft:generic.max_health", 90.0)
		entity.add("minecraft:generic.attack_damage", 11.0)
		entity.add("minecraft:generic.armor", 26.0)
		entity.add("minecraft:generic.movement_speed", 0.45)
		entity.add("minecraft:generic.follow_range", 64.0)
		entity.add("forge:step_height_addition", 2.0)
	})
	event.modify('zombie_extreme:fetus', entity => { 
		entity.add("minecraft:generic.max_health", 120.0)
		entity.add("minecraft:generic.attack_damage", 13.0)
		entity.add("minecraft:generic.armor", 30.0)
		entity.add("minecraft:generic.movement_speed", 0.3)
		entity.add("minecraft:generic.follow_range", 64.0)
		entity.add("forge:step_height_addition", 1.0)
	})
	event.modify('zombie_extreme:explosive_infected', entity => { 
		entity.add("minecraft:generic.max_health", 60.0)
		entity.add("minecraft:generic.attack_damage", 12.0)
		entity.add("minecraft:generic.armor", 16.0)
		entity.add("minecraft:generic.movement_speed", 0.24)
		entity.add("minecraft:generic.follow_range", 64.0)
	})
	event.modify('undead_revamp2:thebidy', entity => { 
		entity.add("minecraft:generic.max_health", 10.0)
		entity.add("minecraft:generic.attack_damage", 1.0)
		entity.add("minecraft:generic.armor", 0.0)
		entity.add("minecraft:generic.movement_speed", 0.15)
		entity.add("minecraft:generic.follow_range", 32.0)
	})
	event.modify('zombie_extreme:divided', entity => { 
		entity.add("minecraft:generic.max_health", 90.0)
		entity.add("minecraft:generic.attack_damage", 12.0)
		entity.add("minecraft:generic.armor", 20.0)
		entity.add("minecraft:generic.movement_speed", 0.23)
		entity.add("minecraft:generic.follow_range", 64.0)
	})
	event.modify('zombie_extreme:ram', entity => { 
		entity.add("minecraft:generic.max_health", 160.0)
		entity.add("minecraft:generic.attack_damage", 14.0)
		entity.add("minecraft:generic.armor", 30.0)
		entity.add("minecraft:generic.movement_speed", 0.22)
		entity.add("minecraft:generic.follow_range", 64.0)
	})
	event.modify('undead_revamp2:thespectre', entity => { 
		entity.add("minecraft:generic.max_health", 90.0)
		entity.add("minecraft:generic.attack_damage", 11.0)
		entity.add("minecraft:generic.armor", 10.0)
		entity.add("minecraft:generic.movement_speed", 0.25)
		entity.add("minecraft:generic.follow_range", 64.0)
	})
	event.modify('zombie_extreme:zero_patient', entity => { 
		entity.add("minecraft:generic.max_health", 600.0)
		entity.add("minecraft:generic.attack_damage", 25.0)
		entity.add("minecraft:generic.armor", 40.0)
		entity.add("minecraft:generic.movement_speed", 0.3)
		entity.add("minecraft:generic.follow_range", 96.0)
		entity.add("forge:step_height_addition", 2.0)
	})
	event.modify('zombie_extreme:demolisher', entity => { 
		entity.add("minecraft:generic.max_health", 500.0)
		entity.add("minecraft:generic.attack_damage", 20.0)
		entity.add("minecraft:generic.armor", 60.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
		entity.add("minecraft:generic.follow_range", 96.0)
		entity.add("forge:step_height_addition", 2.0)
	})
	event.modify('zombie_extreme:rat_king', entity => { 
		entity.add("minecraft:generic.max_health", 700.0)
		entity.add("minecraft:generic.attack_damage", 35.0)
		entity.add("minecraft:generic.armor", 30.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
		entity.add("minecraft:generic.follow_range", 96.0)
		entity.add("forge:step_height_addition", 2.0)
	})
	event.modify('undead_revamp2:theheavy', entity => { 
		entity.add("minecraft:generic.max_health", 600.0)
		entity.add("minecraft:generic.attack_damage", 30.0)
		entity.add("minecraft:generic.armor", 35.0)
		entity.add("minecraft:generic.movement_speed", 0.32)
		entity.add("minecraft:generic.follow_range", 96.0)
		entity.add("forge:step_height_addition", 2.0)
	})
	event.modify('undead_revamp2:clogger', entity => { 
		entity.add("minecraft:generic.max_health", 800.0)
		entity.add("minecraft:generic.attack_damage", 25.0)
		entity.add("minecraft:generic.armor", 40.0)
		entity.add("minecraft:generic.movement_speed", 0.3)
		entity.add("minecraft:generic.follow_range", 96.0)
		entity.add("forge:step_height_addition", 2.0)
	})
	event.modify('undead_revamp2:bigsucker', entity => { 
		entity.add("minecraft:generic.max_health", 250.0)
		entity.add("minecraft:generic.attack_damage", 16.0)
		entity.add("minecraft:generic.armor", 30.0)
		entity.add("minecraft:generic.movement_speed", 0.35)
		entity.add("minecraft:generic.follow_range", 128.0)
	})
	event.modify('spore:inf_human', entity => { 
		entity.add("minecraft:generic.max_health", 90.0)
		entity.add("minecraft:generic.attack_damage", 12.0)
		entity.add("minecraft:generic.armor", 16.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
	})
	event.modify('spore:inf_husk', entity => { 
		entity.add("minecraft:generic.max_health", 90.0)
		entity.add("minecraft:generic.attack_damage", 12.0)
		entity.add("minecraft:generic.armor", 18.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
	})
	event.modify('spore:inf_hazmat', entity => { 
		entity.add("minecraft:generic.max_health", 90.0)
		entity.add("minecraft:generic.attack_damage", 12.0)
		entity.add("minecraft:generic.armor", 20.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
	})
	event.modify('spore:plagued', entity => { 
		entity.add("minecraft:generic.max_health", 110.0)
		entity.add("minecraft:generic.attack_damage", 14.0)
		entity.add("minecraft:generic.armor", 24.0)
		entity.add("minecraft:generic.movement_speed", 0.3)
	})
	event.modify('spore:lacerator', entity => { 
		entity.add("minecraft:generic.max_health", 120.0)
		entity.add("minecraft:generic.attack_damage", 16.0)
		entity.add("minecraft:generic.armor", 22.0)
		entity.add("minecraft:generic.movement_speed", 0.3)
	})
	event.modify('spore:biobloob', entity => { 
		entity.add("minecraft:generic.max_health", 120.0)
		entity.add("minecraft:generic.attack_damage", 16.0)
		entity.add("minecraft:generic.armor", 22.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
	})
	event.modify('spore:saugling', entity => { 
		entity.add("minecraft:generic.max_health", 60.0)
		entity.add("minecraft:generic.attack_damage", 11.0)
		entity.add("minecraft:generic.armor", 10.0)
		entity.add("minecraft:generic.movement_speed", 0.3)
	})
	event.modify('spore:knight', entity => { 
		entity.add("minecraft:generic.max_health", 110.0)
		entity.add("minecraft:generic.attack_damage", 14.0)
		entity.add("minecraft:generic.armor", 24.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
	})
	event.modify('spore:griefer', entity => { 
		entity.add("minecraft:generic.max_health", 155.0)
		entity.add("minecraft:generic.attack_damage", 18.0)
		entity.add("minecraft:generic.armor", 26.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
	})
	event.modify('spore:braiomil', entity => { 
		entity.add("minecraft:generic.max_health", 110.0)
		entity.add("minecraft:generic.attack_damage", 13.0)
		entity.add("minecraft:generic.armor", 22.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
	})
	event.modify('spore:busser', entity => { 
		entity.add("minecraft:generic.max_health", 120.0)
		entity.add("minecraft:generic.attack_damage", 14.0)
		entity.add("minecraft:generic.armor", 20.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
	})
	event.modify('spore:leaper', entity => { 
		entity.add("minecraft:generic.max_health", 180.0)
		entity.add("minecraft:generic.attack_damage", 16.0)
		entity.add("minecraft:generic.armor", 24.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
	})
	event.modify('spore:slasher', entity => { 
		entity.add("minecraft:generic.max_health", 100.0)
		entity.add("minecraft:generic.attack_damage", 19.0)
		entity.add("minecraft:generic.armor", 20.0)
		entity.add("minecraft:generic.movement_speed", 0.22)
	})
	event.modify('spore:spitter', entity => { 
		entity.add("minecraft:generic.max_health", 110.0)
		entity.add("minecraft:generic.attack_damage", 11.0)
		entity.add("minecraft:generic.armor", 20.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
	})
	event.modify('spore:howler', entity => { 
		entity.add("minecraft:generic.max_health", 160.0)
		entity.add("minecraft:generic.attack_damage", 17.0)
		entity.add("minecraft:generic.armor", 24.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
	})
	event.modify('spore:stalker', entity => { 
		entity.add("minecraft:generic.max_health", 180.0)
		entity.add("minecraft:generic.attack_damage", 19.0)
		entity.add("minecraft:generic.armor", 26.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
	})
	event.modify('spore:brute', entity => { 
		entity.add("minecraft:generic.max_health", 220.0)
		entity.add("minecraft:generic.attack_damage", 21.0)
		entity.add("minecraft:generic.armor", 40.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
	})
	event.modify('spore:volatile', entity => { 
		entity.add("minecraft:generic.max_health", 200.0)
		entity.add("minecraft:generic.attack_damage", 19.0)
		entity.add("minecraft:generic.armor", 26.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
	})
	event.modify('spore:bloater', entity => { 
		entity.add("minecraft:generic.max_health", 120.0)
		entity.add("minecraft:generic.attack_damage", 14.0)
		entity.add("minecraft:generic.armor", 30.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
	})
	event.modify('spore:inebriater', entity => { 
		entity.add("minecraft:generic.max_health", 80.0)
		entity.add("minecraft:generic.attack_damage", 14.0)
		entity.add("minecraft:generic.armor", 20.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
	})
	event.modify('spore:nuclea', entity => { 
		entity.add("minecraft:generic.max_health", 160.0)
		entity.add("minecraft:generic.attack_damage", 16.0)
		entity.add("minecraft:generic.armor", 24.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
	})
	event.modify('spore:protector', entity => { 
		entity.add("minecraft:generic.max_health", 140.0)
		entity.add("minecraft:generic.attack_damage", 16.0)
		entity.add("minecraft:generic.armor", 36.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
	})
	event.modify('spore:thorn', entity => { 
		entity.add("minecraft:generic.max_health", 120.0)
		entity.add("minecraft:generic.attack_damage", 15.0)
		entity.add("minecraft:generic.armor", 30.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
	})
	event.modify('spore:scavenger', entity => { 
		entity.add("minecraft:generic.max_health", 120.0)
		entity.add("minecraft:generic.attack_damage", 15.0)
		entity.add("minecraft:generic.armor", 20.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
	})
	event.modify('spore:jagd', entity => { 
		entity.add("minecraft:generic.max_health", 140.0)
		entity.add("minecraft:generic.attack_damage", 16.0)
		entity.add("minecraft:generic.armor", 20.0)
		entity.add("minecraft:generic.movement_speed", 0.35)
	})
	event.modify('spore:scamper', entity => { 
		entity.add("minecraft:generic.max_health", 100.0)
		entity.add("minecraft:generic.attack_damage", 18.0)
		entity.add("minecraft:generic.armor", 18.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
	})
	event.modify('spore:gastgaber', entity => { 
		entity.add("minecraft:generic.max_health", 220.0)
		entity.add("minecraft:generic.attack_damage", 17.0)
		entity.add("minecraft:generic.armor", 20.0)
		entity.add("minecraft:generic.movement_speed", 0.2)
	})
	event.modify('spore:specter', entity => { 
		entity.add("minecraft:generic.max_health", 220.0)
		entity.add("minecraft:generic.attack_damage", 23.0)
		entity.add("minecraft:generic.armor", 30.0)
		entity.add("minecraft:generic.movement_speed", 0.35)
	})
	event.modify('spore:vigil', entity => { 
		entity.add("minecraft:generic.max_health", 200.0)
		entity.add("minecraft:generic.attack_damage", 0.0)
		entity.add("minecraft:generic.armor", 20.0)
		entity.add("minecraft:generic.movement_speed", 0.7)
	})
	event.modify('spore:umarmed', entity => { 
		entity.add("minecraft:generic.max_health", 320.0)
		entity.add("minecraft:generic.attack_damage", 21.0)
		entity.add("minecraft:generic.armor", 22.0)
		entity.add("minecraft:generic.movement_speed", 0.7)
	})
	event.modify('spore:usurper', entity => { 
		entity.add("minecraft:generic.max_health", 300.0)
		entity.add("minecraft:generic.attack_damage", 0.0)
		entity.add("minecraft:generic.armor", 20.0)
		entity.add("minecraft:generic.movement_speed", 0.7)
	})
	event.modify('spore:braurei', entity => { 
		entity.add("minecraft:generic.max_health", 360.0)
		entity.add("minecraft:generic.attack_damage", 0.0)
		entity.add("minecraft:generic.armor", 20.0)
		entity.add("minecraft:generic.movement_speed", 0.7)
	})
	event.modify('spore:verva', entity => { 
		entity.add("minecraft:generic.max_health", 100.0)
		entity.add("minecraft:generic.attack_damage", 0.0)
		entity.add("minecraft:generic.armor", 10.0)
		entity.add("minecraft:generic.movement_speed", 0.7)
	})
	event.modify('spore:delusioner', entity => { 
		entity.add("minecraft:generic.max_health", 160.0)
		entity.add("minecraft:generic.attack_damage", 0.0)
		entity.add("minecraft:generic.armor", 10.0)
		entity.add("minecraft:generic.movement_speed", 0.7)
	})
	event.modify('spore:reconstructor', entity => { 
		entity.add("minecraft:generic.max_health", 120.0)
		entity.add("minecraft:generic.attack_damage", 0.0)
		entity.add("minecraft:generic.armor", 16.0)
		entity.add("minecraft:generic.movement_speed", 0.7)
	})
	event.modify('spore:wendigo', entity => { 
		entity.add("minecraft:generic.max_health", 400.0)
		entity.add("minecraft:generic.attack_damage", 52.0)
		entity.add("minecraft:generic.armor", 60.0)
		entity.add("minecraft:generic.movement_speed", 0.3)
	})
	event.modify('spore:inquisitor', entity => { 
		entity.add("minecraft:generic.max_health", 500.0)
		entity.add("minecraft:generic.attack_damage", 42.0)
		entity.add("minecraft:generic.armor", 50.0)
		entity.add("minecraft:generic.movement_speed", 0.3)
	})
	event.modify('spore:brot', entity => { 
		entity.add("minecraft:generic.max_health", 400.0)
		entity.add("minecraft:generic.attack_damage", 32.0)
		entity.add("minecraft:generic.armor", 60.0)
		entity.add("minecraft:generic.movement_speed", 0.3)
	})

})